SELECT AUTHOR_ID,
       AUTHOR_NAME,
       CATEGORY,
       SUM(PRICE * SALES) AS TOTAL_SALES
FROM   BOOK
       JOIN AUTHOR USING(AUTHOR_ID)
       JOIN BOOK_SALES USING(BOOK_ID)
WHERE  SALES_DATE >= DATE '2022-01-01'
       AND SALES_DATE < DATE '2022-02-01'
GROUP  BY AUTHOR_ID,
          AUTHOR_NAME,
          CATEGORY
ORDER  BY AUTHOR_ID,
          CATEGORY DESC