SELECT PRODUCT_CODE,
       PRICE * SUM(SALES_AMOUNT) AS SALES
FROM   PRODUCT
       JOIN OFFLINE_SALE USING(PRODUCT_ID)
GROUP  BY PRODUCT_CODE,
          PRICE
ORDER  BY SALES DESC,
          PRODUCT_CODE