SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
       TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
       GENDER,
       COUNT(DISTINCT USER_ID) AS USERS
FROM   ONLINE_SALE O
       JOIN USER_INFO U USING(USER_ID)
WHERE  GENDER IS NOT NULL
GROUP  BY TO_CHAR(SALES_DATE, 'YYYY'),
          TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')),
          GENDER
ORDER  BY YEAR,
          MONTH,
          GENDER