SELECT WAREHOUSE_ID,
       WAREHOUSE_NAME,
       ADDRESS,
       NVL(FREEZER_YN, 'N') AS FREEZER_YN
FROM   FOOD_WAREHOUSE
WHERE  SUBSTR(ADDRESS, 1, INSTR(ADDRESS, ' ', 1, 1) - 1) = '경기도'
ORDER  BY WAREHOUSE_ID