SELECT CAR_ID,
       TO_CHAR(ROUND(AVG(DURATION), 1), 'FM9999.0') AS AVERAGE_DURATION
FROM   (
        SELECT CAR_ID,
               END_DATE - START_DATE + 1 AS DURATION
        FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
       )
GROUP  BY CAR_ID
HAVING ROUND(AVG(DURATION), 1) >= 7
ORDER  BY ROUND(AVG(DURATION), 1) DESC,
          CAR_ID DESC