WITH JOINED_2021 AS (
     SELECT USER_ID,
            COUNT(*) OVER() AS JOINED_COUNT
     FROM   USER_INFO
     WHERE  JOINED >= DATE '2021-01-01'
            AND JOINED < DATE '2022-01-01'
),   SALE_JOINED_2021 AS (
     SELECT USER_ID,
            TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
            TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
            JOINED_COUNT
     FROM   ONLINE_SALE
            JOIN JOINED_2021 USING(USER_ID)
)

SELECT YEAR,
       MONTH,
       COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT USER_ID) / JOINED_COUNT, 1) AS PURCHASED_RATIO
FROM   SALE_JOINED_2021
GROUP  BY YEAR,
          MONTH,
          JOINED_COUNT
ORDER  BY YEAR,
          MONTH