SELECT PRODUCT_ID,
       PRODUCT_NAME,
       SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM   FOOD_PRODUCT P
       JOIN FOOD_ORDER O USING(PRODUCT_ID)
WHERE  PRODUCE_DATE >= DATE '2022-05-01'
       AND PRODUCE_DATE < DATE '2022-06-01'
GROUP  BY PRODUCT_ID,
          PRODUCT_NAME,
          PRICE
ORDER  BY TOTAL_SALES DESC,
          PRODUCT_ID