SELECT APNT_NO,
       PT_NAME,
       PT_NO,
       A.MCDP_CD AS MCDP_CD,
       DR_NAME,
       APNT_YMD
FROM   APPOINTMENT A
       JOIN PATIENT USING(PT_NO)
       JOIN DOCTOR 
            ON MDDR_ID = DR_ID
WHERE  A.MCDP_CD = 'CS'
       AND APNT_YMD >= DATE '2022-04-13'
       AND APNT_YMD < DATE '2022-04-14'
       AND APNT_CNCL_YN = 'N'
ORDER  BY APNT_YMD