SELECT MEMBER_NAME,
       REVIEW_TEXT,
       TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM   (
        SELECT MEMBER_ID,
               RANK() OVER (ORDER BY COUNT(*) DESC) AS RANK
        FROM   REST_REVIEW
        GROUP  BY MEMBER_ID
       ) 
       JOIN MEMBER_PROFILE USING (MEMBER_ID)
       JOIN REST_REVIEW USING (MEMBER_ID)
WHERE  RANK = 1
ORDER  BY REVIEW_DATE,
          REVIEW_TEXT