SELECT c.ID AS ID,
       c.GENOTYPE AS GENOTYPE,
       p.GENOTYPE AS PARENT_GENOTYPE
FROM   ECOLI_DATA p
       JOIN ECOLI_DATA c
         ON p.ID = c.PARENT_ID
WHERE  (p.GENOTYPE & c.GENOTYPE) = p.GENOTYPE
ORDER  BY c.ID