SELECT MCDP_CD AS 진료과코드,
       COUNT(MCDP_CD) AS "5월예약건수"
FROM   APPOINTMENT
WHERE  APNT_YMD >= DATE '2022-05-01'
       AND APNT_YMD < DATE '2022-06-01'
GROUP  BY MCDP_CD
ORDER  BY "5월예약건수",
          진료과코드