SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE  CAR_ID IN (
            SELECT CAR_ID
            FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE  START_DATE >= DATE '2022-08-01'
                   AND START_DATE < DATE '2022-11-01'
            GROUP  BY CAR_ID
            HAVING COUNT(CAR_ID) >= 5
       )
       AND START_DATE >= DATE '2022-08-01'
       AND START_DATE <  DATE '2022-11-01'
GROUP  BY CAR_ID, EXTRACT(MONTH FROM START_DATE)
ORDER  BY MONTH,
          CAR_ID DESC