SELECT
    YEAR,
    MAX_SIZE_OF_COLONY - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
    JOIN (
        SELECT
            YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
        FROM
            ECOLI_DATA
        GROUP BY
            YEAR(DIFFERENTIATION_DATE)
    ) AS MAX_YEAR
    ON YEAR(DIFFERENTIATION_DATE) = MAX_YEAR.YEAR
ORDER BY
    YEAR,
    YEAR_DEV
