SELECT C.CAR_ID
FROM   CAR_RENTAL_COMPANY_CAR C
       JOIN (
            SELECT DISTINCT CAR_ID
            FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE  TO_CHAR(START_DATE, 'MM') = 10
       ) H
       ON C.CAR_ID = H.CAR_ID
WHERE  CAR_TYPE = '세단'
ORDER  BY C.CAR_ID DESC