SELECT BOOK_ID,
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE_STR
FROM   BOOK
WHERE  PUBLISHED_DATE >= '2021-01-01'
  AND  PUBLISHED_DATE <  '2022-01-01'
  AND  CATEGORY = '인문'
ORDER  BY PUBLISHED_DATE;